config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Create
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'

  # Read All and One
  get 'tasks', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show', as: :task

  # Update
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  # Delete
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # Create

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  # Read

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  # Update

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(edit_task_params)
    redirect_to task_path(@task)
  end

  # Delete

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def edit_task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Update <%= @task.title %></h1>

<%= form_for(@task) do |task|%>
  <%= task.label :title %>
  <%= task.text_field :title %>
  <%= task.label :details %>
  <%= task.text_field :details %>
  <%= task.check_box :completed %>
  <%= task.label :completed %>
  <%= task.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<% @tasks.each do |task| %>
  <div>
    <% if task.completed %>
    <input type="checkbox" checked>
    <% else %>
    <input type="checkbox">
    <% end %>
    <label><%= link_to task.title, task_path(task) %>: <%= task.details %></label>
  </div>
<% end %>

<br>
<br>

<div>
  <%= link_to 'Create new task', new_task_path(@task) %>
</div>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>

<%= form_for(@task) do |task|%>
  <%= task.label :title %>
  <%= task.text_field :title %>
  <%= task.label :details %>
  <%= task.text_field :details %>
  <%= task.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>Task: <%= @task.title %></h1>

<p><strong>Details</strong></p>
<p><%= @task.details %></p>

<p><strong>Completed:</strong> <%= @task.completed %></p>

<br>
<br>

<div>
  <%= link_to 'Update this task', edit_task_path(@task) %>
  <%= link_to 'Delete this task', delete_task_path(@task), method: :delete, data: { confirm: "Are you sure?" } %>
</div>